---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ meta.name }}"
  namespace: "{{ meta.namespace }}"
spec:
  replicas: {{ size | int }}
  selector:
    matchLabels:
      app: imo
  template:
    metadata:
      labels:
        app: imo
    spec:
      containers:
        - name: imo
          image: nginx
          ports:
            - containerPort: 80
