apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imos.imo.example.com
  namespace: imokuri
spec:
  group: imo.example.com
  names:
    kind: Imo
    listKind: ImoList
    plural: imos
    singular: imo
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
