apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kabochas.kabocha.example.com
  namespace: imokuri
spec:
  group: kabocha.example.com
  names:
    kind: Kabocha
    listKind: KabochaList
    plural: kabochas
    singular: kabocha
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
