apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: katsudons.katsudon.example.com
  namespace: imokuri
spec:
  group: katsudon.example.com
  names:
    kind: KatsuDon
    listKind: KatsuDonList
    plural: katsudons
    singular: katsudon
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
