apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kuris.kuri.example.com
spec:
  group: kuri.example.com
  names:
    kind: Kuri
    listKind: KuriList
    plural: kuris
    singular: kuri
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
