apiVersion: apps/v1
kind: Deployment
metadata:
  name: imo-operator
  namespace: imokuri
spec:
  replicas: 1
  selector:
    matchLabels:
      name: imo-operator
  template:
    metadata:
      labels:
        name: imo-operator
    spec:
      serviceAccountName: imo-operator
      containers:
        - name: ansible
          command:
            - /usr/local/bin/ao-logs
            - /tmp/ansible-operator/runner
            - stdout
          # Replace this with the built image name
          image: "quay.io/imokuri/imo-operator:v0.0.1"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
              readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "quay.io/imokuri/imo-operator:v0.0.1"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "imo-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
