kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imo-operator
  namespace: imokuri
subjects:
  - kind: ServiceAccount
    name: imo-operator
    namespace: imokuri
roleRef:
  kind: Role
  name: imo-operator
  apiGroup: rbac.authorization.k8s.io
