---
- name: Deploy Imo
  k8s:
    state: "{{ state | default(omit) }}"
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
      spec:
        replicas: "{{ size }}"
        selector:
          matchLabels:
            app: imo
        template:
          metadata:
            labels:
              app: imo
          spec:
            containers:
              - name: imo
                image: nginx
                ports:
                  - containerPort: 80

- name: Deploy Imo service
  k8s:
    state: "{{ state | default(omit) }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
        labels:
          app: imo
      spec:
        type: LoadBalancer
        ports:
          - port: 80
            targetPort: 80
        selector:
          app: imo
