---
- name: Deploy Imo
  k8s:
    state: "{{ state | default(omit) }}"
    definition: "{{ lookup('template', 'deploy.yaml') }}"

- name: Deploy Imo service
  k8s:
    state: "{{ state | default(omit) }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
        labels:
          app: imo
      spec:
        type: LoadBalancer
        ports:
          - port: 80
            targetPort: 80
        selector:
          app: imo
